global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      timeout: 10s
      api_version: v2

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics (existing discovery service)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Discovery Cluster Application Metrics
  - job_name: 'discovery-cluster'
    static_configs:
      - targets: ['discovery-cluster:8001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Execution Cluster Application Metrics
  - job_name: 'execution-cluster'
    static_configs:
      - targets: ['execution-cluster:8001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # Risk Cluster Application Metrics
  - job_name: 'risk-cluster'
    static_configs:
      - targets: ['risk-cluster:8001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # PostgreSQL Database Metrics (existing discovery service)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 30s

  # Redis Cache Metrics (existing discovery service)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']
    scrape_interval: 30s

  # Pulsar Message Broker Metrics (existing discovery service)
  - job_name: 'pulsar'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # NGINX Load Balancer Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Elasticsearch Metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Custom Trading Platform Metrics
  - job_name: 'trading-platform'
    static_configs:
      - targets: 
          - 'discovery-cluster:8000'
          - 'execution-cluster:8000' 
          - 'risk-cluster:8000'
    scrape_interval: 10s
    metrics_path: '/health'
    params:
      format: ['prometheus']

# Alertmanager configuration (for future implementation)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093 